# Generated by Django 3.0.2 on 2020-02-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brick',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
